development:
 adapter: postgresql
 database: library_app
 username: postgres
 password: 
 host: 127.0.0.1
 
 
test:
 adapter: postgresql
 database: library_app_test
 username: postgres
 password:
 host: 127.0.0.1